name: Unit Tests

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  go-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.3'
      - name: Install Modules
        working-directory: ./go
        run: |
          go mod download
      - name: Run Unit Tests
        working-directory: ./go
        run: |
          go test -json ./...
